site_name: fran.blog
site_url: https://fsilavong.github.io/
theme:
  name: material
  palette:
    primary: black
    scheme: slate
    accent: lime
  font:
    text: Infer
    code: JetBrains Mono
  features:
    - navigation.instant
  favicon: images/favicon.svg
plugins:
  - blog
extra_css:
  - stylesheets/terminal.css
markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
nav:
  - index.md
  - Blog:
    - blog/index.md
extra:
  analytics:
    provider: google
    property: G-M8M680K2JW