site_name: fran.blog
site_url: https://fsilavong.github.io/
theme:
  name: material
  palette:
    primary: black
    scheme: slate
    accent: lime
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  features:
    - navigation.instant
  favicon: images/favicon.svg
plugins:
  - blog
extra_css:
  - stylesheets/terminal.css
markdown_extensions:
  - codehilite
  - pymdownx.superfences
nav:
  - index.md
  - Blog:
    - blog/index.md
